### PR TITLE
Add new compendium with the ready-to-use map of Mouse Territories

### PR DESCRIPTION
**Pull request by ZwS**
Also, map files were converted into actual webp (they were PNGs renamed to webp)

### CODE REVIEW

**Comment by ZwS** [comment]
I guess that it would be also nice to add journal with the cities (just empty sections named after the cities without descriptions) and add them as the notes to this map. Unfortunately I don't have the English rulebook and some handwriting the map is hardly recognizable for me.

**Comment by jsavko** [comment]
That info can't be distributed with the current license

**Comment by jsavko** [comment]
Additionally I forgot the map was included and will be removed in the next release

**Comment by ZwS** [comment]
Oh well, that's bad. I supposed that it's possible to use that map.

**Comment by jsavko** [comment]
The map I also don't have a license to distribute and shouldn't have been in the system. I simply forgot to remove it.  It will be removed in the next release

**Pull request closed without merging**
