### PR TITLE
Character sheet update

### PR DESCRIPTION
**Pull request by ZwS**
Hi,

I've made some changes in the sheets layout. Most for them are targeted to improve i18n of the system, since some translated strings are longer than English equivalents and do not fit. 
There are also some cosmetic changes like moving name and portrait to the top of the sheet so they are always visible, and adding cute mouse icon as a default character image.

screenshot

### CODE REVIEW

**Comment by jsavko** [comment]
Where did the art for the mouse come from? It needs to be properly credited

**Comment by ZwS** [comment]
It's from the game-icons.net

https://game-icons.net/1x1/lorc/seated-mouse.html

**Comment by jsavko** [comment]
I like the sheet redesign. I've got some other updates scheduled for this system when I have some time to implement them. I will merge this into the code base after some testing

**Comment by jsavko** [comment]
Looks like it's the same icon that is already in the system assets folder

**Pull request merged**
